# Common settings across environments

appName: "Spring-Boot API"

image:
  repository: busybox
  tag: "stable"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  ports:
    - port: 8080
    - port: 8081
    - port: 8082

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

config:
  jsonData: |
    {
      "key": "value",
      "anotherKey": "anotherValue"
    }

deployment:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

livenessProbe:
  tcpSocket:
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  tcpSocket:
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10
