apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}
  labels:
    app: {{ include "mychart.name" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
    - port: 8081
      targetPort: 8081
      protocol: TCP
    - port: 8082
      targetPort: 8082
      protocol: TCP
  selector:
    app: {{ include "mychart.name" . }}
    release: {{ .Release.Name }}
